## Lecture 2: reading image, basic review of `numpy` and Linear Algebra

In [ ]:
import numpy as np

import matplotlib.pyplot as plt
from matplotlib import rc

plt.rcParams['xtick.labelsize']=20      # change the tick label size for x axis
plt.rcParams['ytick.labelsize']=20      # change the tick label size for x axis
plt.rcParams['axes.linewidth']=1        # change the line width of the axis
plt.rcParams['xtick.major.width'] = 3   # change the tick line width of x axis
plt.rcParams['ytick.major.width'] = 3   # change the tick line width of y axis
rc('text', usetex=False)                # disable LaTeX rendering in plots
rc('font',**{'family':'DejaVu Sans'})   # set the font of the plot to be DejaVu Sans

### 0. Read File from Google Drive
In this course, we will need data that we did not generate ourselves, so it is crucial to learn how to read data into Python.

If you are using Python on your own computer, then you will not need to worry about mounting your Google Drive in your Jupyter Notebook.  If you are using Google Colab, then the next step is crucial.

#### Mounting Google Drive to Colab

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# you can use bash commands in Python environment by putting "!" at the
# beginning of the command
!pwd # this is a bash command to print (p) working (w) directory (d)

Mounted at /content/drive
/content


#### Getting to the correct directory

1. **Safest choice**: you can always hard code the absolute directory path
2. **Convenient choice**: you can use `os.chdir` to change to your desired working directory (caution: you need to always pay attention which directory you are in when going through your code)

`os` is a very useful package for navigating your operating/file systems. There are many tutorials for the `os` package online. If you are curious to learn more, search for "python os tutorial".


In [ ]:
import os

# Method 1
path = "/content/drive/MyDrive/ME491"
image_path = os.path.join(path, "image/dog.jpg")
print(image_path)

/content/drive/MyDrive/ME491/image/dog.jpg


In [ ]:
# Method 2
os.chdir(path)
!pwd

/content/drive/MyDrive/ME491


### 1. Read Image

Documentation on `plt.imshow`: https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imshow.html

In [ ]:
from matplotlib.image import imread

A = imread(image_path)
plt.imshow(A)

Now let's look at what's in $A$

Normally, when converting images to data,  we will reduce the image to grayscale.

Let's plot the image again.

### 2. Basic `Numpy` Recap

2.1. Array Generation

In [ ]:
# generate a 1D array (vector) of 10 zeros
a = np.zeros(10)
# generate a 2D array (matrix) of [4, 4] ones
b = np.ones((4, 4))
# generate a 2D array (matrix) of [3, 3] ones
c = np.random.rand(3, 3)
print(a, '\n', b, '\n', c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 [[0.61035948 0.37020884 0.28512825]
 [0.54553086 0.61349398 0.86333552]
 [0.91714648 0.46828653 0.70222766]]


2.2 Array Slicing

In [ ]:
X_1 = np.random.randint(low=1, high=6, size=(4, 4))
X_2 = np.random.randint(low=1, high=6, size=(4, 4))
print("Array 1 is: \n", X_1)
print("Array 2 is: \n", X_2)
print(X_1[1::, :])

Array 1 is: 
 [[3 1 2 2]
 [1 3 5 3]
 [3 4 3 3]
 [3 5 3 2]]
Array 2 is: 
 [[1 3 4 5]
 [5 2 4 5]
 [2 3 3 3]
 [3 3 4 5]]
[[1 3 5 3]
 [3 4 3 3]
 [3 5 3 2]]


2.3 Some Useful `Numpy` Commands

In [ ]:
# Getting the dimension of an array
print(np.shape(A))

(2000, 1500, 3)


### 3. Linear Algebra Review

Recall an $m\times n$ matrix $A$ can be represented as:
$$A = \begin{bmatrix}
    a_{11} & a_{12} & a_{13} & \dots  & a_{1n} \\
    a_{21} & a_{22} & a_{23} & \dots  & a_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    a_{m1} & a_{m2} & a_{m3} & \dots  & a_{mn}
\end{bmatrix}$$




In [ ]:
# Let's generate two random matrices
A = np.random.randint(low=1, high=6, size=(4, 4))
B = np.random.randint(low=1, high=6, size=(4, 4))
print("Array A is: \n", A)
print("Array B is: \n", B)

3.1 Matrix Addition

The sum $A+B$ of two $m\times n$ matrices $A$ and $B$ is calculated entry wise:

$$ (A+B)_{ij} = A_{ij}+B_{ij}$$

In [ ]:
# element-wise addition
print("Element-wise addition for A and B is: \n", )

Similarly, you can do element-wise subtraction, multiplication and division.

In [ ]:
# element-wise subtraction
print("Element-wise subtraction for A and B is: \n", )
# element-wise multiplication
print("Element-wise multiplication for A and B is: \n", )
# element-wise division
print("Element-wise division for A and B is: \n", )

3.2 Scalar Multiplication

The product $cA$ of a number $c$ and a matrix $A$ is computed by multiplying every entry of $A$ by $c$:

$$ (cA)_{ij} = c\cdot A_{ij}$$

In [ ]:
# scalar multiplication
c = np.random.randint(low=-6, high=6)
print(c)
print("Scalar multiplication for scalar c and matrix A is: \n", )

3.3 Transposition

The transpose of an $m\times n$ matrix is the $n\times m$ matrix $A^T$ formed by turning rows into columns and vice versa:

$$ (A^T)_{ij} = A_{ji}$$

In [ ]:
print("The transpose of matrix A is: \n", )

3.4 Matrix Multiplication

$$ [AB]_{ij} = a_{i1}b_{1j}+a_{i2}b_{2j}+\cdots+a_{in}b_{nj}=\sum_{r=1}^n a_{ir}b_{rj}$$

In [ ]:
# Matrix Multiplication
print("Matrix Multiplication for A and B is: \n", )

Matrix multiplication does not commute:
$$AB\neq BA$$

In [ ]:
print("Matrix Multiplication for B and A is: \n", )

3.5 Identity Matrix

The identity matrix is a square matrix of any arbitrary size with ones on the main diagonal and zeros elsewhere.

For a matrix $A$ with size $m\times n$, we have:
$$ I_mA=AI_n=A $$

In [ ]:
# It's very easy to generate an identity matrix in numpy


3.6 Determinant of a matrix

The determinant of a $2\times2$ matrix is
$$ \det(A) = \det\left(\begin{bmatrix}
    a & b  \\
    c & d
\end{bmatrix}\right)=ad-bc$$

The determinant of a $3\times3$ matrix is
$$ \det(A) = \det\left(\begin{bmatrix}
    a & b & c  \\
    d & e & f  \\
    g & h & i
\end{bmatrix}\right)=aei+bfg+cdh-ceg-fha-ibd$$

In [ ]:
# numpy has convenient functions to compute the determinant of a given matrix
print("The determinant of A is: ", )

3.7 Matrix Inverse

For a square matrix $A$, its inverse $A^{-1}$ has the following property
$$A^{-1}A=AA^{-1}=I$$

Note: not all square matrices have inverses, a square matrix has an inverse *if and only if* the determinant of the matrix is not zero.

In [ ]:
# again, we can use numpy to find the inverse of a matrix
A_inv =
print("The inverse of A is: \n", A_inv)

3.8 Eigenvalues/vectors of a Square Matrix

For a square matrix $A$, we have:

$$ Ax=\lambda x$$

all scalar value $\lambda$s that satisfy the above equation are *eigenvalues* of $A$, while all vector $x$s that satisfy the above equation are *eigenvectors* of $A$.

Eigenvalues and eigenvectors are very useful in matrix decomopositions, which we will use a lot in this course.

In [ ]:
# for now, let's just use numpy to find eigenvalues/vectors for a matrix
eigenvalues, eigenvectors =
print("Eigenvalues for A are: \n", eigenvalues)
print("Eigenvectors for A are: \n", eigenvectors)

3.9 Eigen decomposition

Once we have the eigenvalues and eigenvectors for a matrix, we can decompose the matrix into three parts
1. a matrix consists of all eigenvectors $Q$
2. a diagonal matrix where the eigenvalues are on the diagonals in the same order as the eigenvector matrix $\Lambda$
3. the inverse of the eigenvector matrix $Q^{-1}$

$$ A = Q\Lambda Q^{-1}$$

In [ ]:
# Let's test it in numpy
print(A)
Lambda = np.diag(eigenvalues) # turn a vector into a diagonal matrix
print(eigenvectors @ Lambda @ np.linalg.inv(eigenvectors))

3.10 Inner Product

Inner product for vectors is the same as the dot product, but it can be extended to higher dimensions.

In [ ]:
a =
b =
print(a)
print(a.shape)
print(b)
print(b.shape)
c =
print(c)
print(c.shape)

3.11 Outer Product

For two vectors $u$ ($m\times1$) and $v$ ($n\times1$), where:
$$ u = \begin{bmatrix}
    u_1  \\
    u_2  \\
    \vdots \\
    u_m
\end{bmatrix}, \qquad v = \begin{bmatrix}
    v_1  \\
    v_2  \\
    \vdots \\
    v_n
\end{bmatrix}$$

The outer product of $u\otimes v$ is a matrix of shape $m\times n$:
$$\begin{bmatrix}
    u_1v_1 & u_1v_2 & \cdots & u_1v_n  \\
    u_2v_1 & u_2v_2 & \cdots & u_2v_n  \\
    \vdots & \vdots & \ddots & \vdots \\
    u_mv_1 & u_mv_2 & \cdots & u_mv_n
\end{bmatrix}$$

In [ ]:
a =
b =
print(a)
print(a.shape)
print(b)
print(b.shape)
c =
print(c)
print(c.shape)

### Extra: image compression

In [ ]:
X = np.mean(A, -1); # Convert RGB to grayscale
img = plt.imshow(X)
# Take the SVD
U, S, VT = np.linalg.svd(X,full_matrices=False)
S = np.diag(S)

In [ ]:
for r in [5, 20, 100]: # Construct approximate image
  Xapprox = U[:,:r] @ S[0:r,:r] @ VT[:r,:]
  img = plt.imshow(Xapprox, cmap='Greys_r')
  plt.show()